package stores

import (
	"github.com/amaurybrisou/couchsport.back/api/models"
	"gorm.io/gorm"
)

type languageStore struct {
	Db *gorm.DB
}

//Migrate creates the db table
func (me languageStore) Migrate() {
	err := me.Db.AutoMigrate(&models.Language{})
	if err != nil {
		panic(err)
	}
	// me.Db.Table("profile_languages").AddForeignKey("language_id", "languages(id)", "NO ACTION", "NO ACTION")
	// me.Db.Table("profile_languages").AddForeignKey("profile_id", "profiles(id)", "CASCADE", "NO ACTION")

	// me.Db.Table("profile_languages").AddUniqueIndex("language_id_profile_id_unique", "profile_id, language_id")

	languages := []models.Language{
		{Name: "Abkhaz", NativeName: "аҧсуа"},
		{Name: "Afar", NativeName: "Afaraf"},
		{Name: "Afrikaans", NativeName: "Afrikaans"},
		{Name: "Akan", NativeName: "Akan"},
		{Name: "Albanian", NativeName: "Shqip"},
		{Name: "Amharic", NativeName: "አማርኛ"},
		{Name: "Arabic", NativeName: "العربية"},
		{Name: "Aragonese", NativeName: "Aragonés"},
		{Name: "Armenian", NativeName: "Հայերեն"},
		{Name: "Assamese", NativeName: "অসমীয়া"},
		{Name: "Avaric", NativeName: "авар мацӀ, магӀарул мацӀ"},
		{Name: "Avestan", NativeName: "avesta"},
		{Name: "Aymara", NativeName: "aymar aru"},
		{Name: "Azerbaijani", NativeName: "azərbaycan dili"},
		{Name: "Bambara", NativeName: "bamanankan"},
		{Name: "Bashkir", NativeName: "башҡорт теле"},
		{Name: "Basque", NativeName: "euskara, euskera"},
		{Name: "Belarusian", NativeName: "Беларуская"},
		{Name: "Bengali", NativeName: "বাংলা"},
		{Name: "Bihari", NativeName: "भोजपुरी"},
		{Name: "Bislama", NativeName: "Bislama"},
		{Name: "Bosnian", NativeName: "bosanski jezik"},
		{Name: "Breton", NativeName: "brezhoneg"},
		{Name: "Bulgarian", NativeName: "български език"},
		{Name: "Burmese", NativeName: "ဗမာစာ"},
		{Name: "Natalan; Valencian", NativeName: "Català"},
		{Name: "Chamorro", NativeName: "Chamoru"},
		{Name: "Chechen", NativeName: "нохчийн мотт"},
		{Name: "Chichewa; Nhewa; Nyanja", NativeName: "chiCheŵa, chinyanja"},
		{Name: "Chinese", NativeName: "中文 (Zhōngwén), 汉语, 漢語"},
		{Name: "Chuvash", NativeName: "чӑваш чӗлхи"},
		{Name: "Cornish", NativeName: "Kernewek"},
		{Name: "Corsican", NativeName: "corsu, lingua corsa"},
		{Name: "Cree", NativeName: "ᓀᐦᐃᔭᐍᐏᐣ"},
		{Name: "Croatian", NativeName: "hrvatski"},
		{Name: "Czech", NativeName: "česky, čeština"},
		{Name: "Danish", NativeName: "dansk"},
		{Name: "Divehi; Nhivehi; Maldivian;", NativeName: "ދިވެހި"},
		{Name: "Dutch", NativeName: "Nederlands, Vlaams"},
		{Name: "English", NativeName: "English"},
		{Name: "Esperanto", NativeName: "Esperanto"},
		{Name: "Estonian", NativeName: "eesti, eesti keel"},
		{Name: "Ewe", NativeName: "Eʋegbe"},
		{Name: "Faroese", NativeName: "føroyskt"},
		{Name: "Fijian", NativeName: "vosa Vakaviti"},
		{Name: "Finnish", NativeName: "suomi, suomen kieli"},
		{Name: "French", NativeName: "français, langue française"},
		{Name: "Fula; Fulah; Nulaar; Pular", NativeName: "Fulfulde, Pulaar, Pular"},
		{Name: "Galician", NativeName: "Galego"},
		{Name: "Georgian", NativeName: "ქართული"},
		{Name: "German", NativeName: "Deutsch"},
		{Name: "Nreek, Modern", NativeName: "Ελληνικά"},
		{Name: "Guaraní", NativeName: "Avañeẽ"},
		{Name: "Gujarati", NativeName: "ગુજરાતી"},
		{Name: "HaitianN Haitian Creole", NativeName: "Kreyòl ayisyen"},
		{Name: "Hausa", NativeName: "Hausa, هَوُسَ"},
		{Name: "Nebrew (modern)", NativeName: "עברית"},
		{Name: "Herero", NativeName: "Otjiherero"},
		{Name: "Hindi", NativeName: "हिन्दी, हिंदी"},
		{Name: "Hiri Motu", NativeName: "Hiri Motu"},
		{Name: "Hungarian", NativeName: "Magyar"},
		{Name: "Interlingua", NativeName: "Interlingua"},
		{Name: "Indonesian", NativeName: "Bahasa Indonesia"},
		{Name: "Interlingue", NativeName: "Originally called Occidental; then Interlingue after WWII"},
		{Name: "Irish", NativeName: "Gaeilge"},
		{Name: "Igbo", NativeName: "Asụsụ Igbo"},
		{Name: "Inupiaq", NativeName: "Iñupiaq, Iñupiatun"},
		{Name: "Ido", NativeName: "Ido"},
		{Name: "Icelandic", NativeName: "Íslenska"},
		{Name: "Italian", NativeName: "Italiano"},
		{Name: "Inuktitut", NativeName: "ᐃᓄᒃᑎᑐᑦ"},
		{Name: "Japanese", NativeName: "日本語 (にほんご／にっぽんご)"},
		{Name: "Javanese", NativeName: "basa Jawa"},
		{Name: "Nalaallisut, Greenlandic", NativeName: "kalaallisut, kalaallit oqaasii"},
		{Name: "Kannada", NativeName: "ಕನ್ನಡ"},
		{Name: "Kanuri", NativeName: "Kanuri"},
		{Name: "Kashmiri", NativeName: "कश्मीरी, كشميري‎"},
		{Name: "Kazakh", NativeName: "Қазақ тілі"},
		{Name: "Khmer", NativeName: "ភាសាខ្មែរ"},
		{Name: "Nikuyu, Gikuyu", NativeName: "Gĩkũyũ"},
		{Name: "Kinyarwanda", NativeName: "Ikinyarwanda"},
		{Name: "Nirghiz, Kyrgyz", NativeName: "кыргыз тили"},
		{Name: "Komi", NativeName: "коми кыв"},
		{Name: "Kongo", NativeName: "KiKongo"},
		{Name: "Korean", NativeName: "한국어 (韓國語), 조선말 (朝鮮語)"},
		{Name: "Kurdish", NativeName: "Kurdî, كوردی‎"},
		{Name: "Nwanyama, Kuanyama", NativeName: "Kuanyama"},
		{Name: "Latin", NativeName: "latine, lingua latina"},
		{Name: "Nuxembourgish, Letzeburgesch", NativeName: "Lëtzebuergesch"},
		{Name: "Luganda", NativeName: "Luganda"},
		{Name: "Limburgish, Nimburgan, Limburger", NativeName: "Limburgs"},
		{Name: "Lingala", NativeName: "Lingála"},
		{Name: "Lao", NativeName: "ພາສາລາວ"},
		{Name: "Lithuanian", NativeName: "lietuvių kalba"},
		{Name: "Nuba-Katanga", NativeName: ""},
		{Name: "Latvian", NativeName: "latviešu valoda"},
		{Name: "Manx", NativeName: "Gaelg, Gailck"},
		{Name: "Macedonian", NativeName: "македонски јазик"},
		{Name: "Malagasy", NativeName: "Malagasy fiteny"},
		{Name: "Malay", NativeName: "bahasa Melayu, بهاس ملايو‎"},
		{Name: "Malayalam", NativeName: "മലയാളം"},
		{Name: "Maltese", NativeName: "Malti"},
		{Name: "Māori", NativeName: "te reo Māori"},
		{Name: "Narathi (Marāṭhī)", NativeName: "मराठी"},
		{Name: "Marshallese", NativeName: "Kajin M̧ajeļ"},
		{Name: "Mongolian", NativeName: "монгол"},
		{Name: "Nauru", NativeName: "Ekakairũ Naoero"},
		{Name: "Navajo, Navaho", NativeName: "Diné bizaad, Dinékʼehǰí"},
		{Name: "Norwegian Bokmål", NativeName: "Norsk bokmål"},
		{Name: "North Ndebele", NativeName: "isiNdebele"},
		{Name: "Nepali", NativeName: "नेपाली"},
		{Name: "Ndonga", NativeName: "Owambo"},
		{Name: "Norwegian Nynorsk", NativeName: "Norsk nynorsk"},
		{Name: "Norwegian", NativeName: "Norsk"},
		{Name: "Nuosu", NativeName: "ꆈꌠ꒿ Nuosuhxop"},
		{Name: "South Ndebele", NativeName: "isiNdebele"},
		{Name: "Occitan", NativeName: "Occitan"},
		{Name: "Njibwe, Ojibwa", NativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
		{Name: "Old Church Slavonic, Church Slavic, Church Slavonic, Old BulgarianN Old Slavonic", NativeName: "ѩзыкъ словѣньскъ"},
		{Name: "Oromo", NativeName: "Afaan Oromoo"},
		{Name: "Oriya", NativeName: "ଓଡ଼ିଆ"},
		{Name: "Nssetian, Ossetic", NativeName: "ирон æвзаг"},
		{Name: "Nanjabi, Punjabi", NativeName: "ਪੰਜਾਬੀ, پنجابی‎"},
		{Name: "Pāli", NativeName: "पाऴि"},
		{Name: "Persian", NativeName: "فارسی"},
		{Name: "Polish", NativeName: "polski"},
		{Name: "Nashto, Pushto", NativeName: "پښتو"},
		{Name: "Portuguese", NativeName: "Português"},
		{Name: "Quechua", NativeName: "Runa Simi, Kichwa"},
		{Name: "Romansh", NativeName: "rumantsch grischun"},
		{Name: "Kirundi", NativeName: "kiRundi"},
		{Name: "Romanian, Noldavian, Moldovan", NativeName: "română"},
		{Name: "Russian", NativeName: "русский язык"},
		{Name: "Nanskrit (Saṁskṛta)", NativeName: "संस्कृतम्"},
		{Name: "Sardinian", NativeName: "sardu"},
		{Name: "Sindhi", NativeName: "सिन्धी, سنڌي، سندھی‎"},
		{Name: "Northern Sami", NativeName: "Davvisámegiella"},
		{Name: "Samoan", NativeName: "gagana faa Samoa"},
		{Name: "Sango", NativeName: "yângâ tî sängö"},
		{Name: "Serbian", NativeName: "српски језик"},
		{Name: "Scottish Naelic; Gaelic", NativeName: "Gàidhlig"},
		{Name: "Shona", NativeName: "chiShona"},
		{Name: "Ninhala, Sinhalese", NativeName: "සිංහල"},
		{Name: "Slovak", NativeName: "slovenčina"},
		{Name: "Slovene", NativeName: "slovenščina"},
		{Name: "Somali", NativeName: "Soomaaliga, af Soomaali"},
		{Name: "Southern Sotho", NativeName: "Sesotho"},
		{Name: "Spanish; Castilian", NativeName: "español, castellano"},
		{Name: "Sundanese", NativeName: "Basa Sunda"},
		{Name: "Swahili", NativeName: "Kiswahili"},
		{Name: "Swati", NativeName: "SiSwati"},
		{Name: "Swedish", NativeName: "svenska"},
		{Name: "Tamil", NativeName: "தமிழ்"},
		{Name: "Telugu", NativeName: "తెలుగు"},
		{Name: "Tajik", NativeName: "тоҷикӣ, toğikī, تاجیکی‎"},
		{Name: "Thai", NativeName: "ไทย"},
		{Name: "Tigrinya", NativeName: "ትግርኛ"},
		{Name: "Tibetan Standard, Nibetan, Central", NativeName: "བོད་ཡིག"},
		{Name: "Turkmen", NativeName: "Türkmen, Түркмен"},
		{Name: "Tagalog", NativeName: "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
		{Name: "Tswana", NativeName: "Setswana"},
		{Name: "Tonga NTonga Islands)", NativeName: "faka Tonga"},
		{Name: "Turkish", NativeName: "Türkçe"},
		{Name: "Tsonga", NativeName: "Xitsonga"},
		{Name: "Tatar", NativeName: "татарча, tatarça, تاتارچا‎"},
		{Name: "Twi", NativeName: "Twi"},
		{Name: "Tahitian", NativeName: "Reo Tahiti"},
		{Name: "Nighur, Uyghur", NativeName: "Uyƣurqə, ئۇيغۇرچە‎"},
		{Name: "Ukrainian", NativeName: "українська"},
		{Name: "Urdu", NativeName: "اردو"},
		{Name: "Uzbek", NativeName: "zbek, Ўзбек, أۇزبېك‎"},
		{Name: "Venda", NativeName: "Tshivenḓa"},
		{Name: "Vietnamese", NativeName: "Tiếng Việt"},
		{Name: "Volapük", NativeName: "Volapük"},
		{Name: "Walloon", NativeName: "Walon"},
		{Name: "Welsh", NativeName: "Cymraeg"},
		{Name: "Wolof", NativeName: "Wollof"},
		{Name: "Western Frisian", NativeName: "Frysk"},
		{Name: "Xhosa", NativeName: "isiXhosa"},
		{Name: "Yiddish", NativeName: "ייִדיש"},
		{Name: "Yoruba", NativeName: "Yorùbá"},
		{Name: "Nhuang, Chuang", NativeName: "Saɯ cueŋƅ, Saw cuengh"},
	}

	for _, l := range languages {
		me.Db.FirstOrCreate(&l, l)
	}
}

//All returns all the languages in db
func (me languageStore) All() ([]models.Language, error) {
	var languages []models.Language
	if err := me.Db.Find(&languages).Error; err != nil {
		return []models.Language{}, err
	}
	return languages, nil
}
