name: "Deploy to prod"

on:
  workflow_dispatch:

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ github.sha }}
      UPLOAD_PATH: ${{ secrets.REMOTE_TARGET }}/${{github.sha }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SERVER_SSH_KEY_PASSPHRASE: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create hash directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{  env.REMOTE_USER }}
          key: ${{  env.SERVER_SSH_KEY }}
          passphrase: ${{  env.SERVER_SSH_KEY_PASSPHRASE }}
          envs: UPLOAD_PATH,REMOTE_USER
          script_stop: true
          script: |
            mkdir "$UPLOAD_PATH"

      - name: Deploy to Server (scp)
        uses: appleboy/scp-action@master
        with:
          source: "couchsport.back/localizer,couchsport.back/fixtures/acouch.sql,couchsport.front/static"
          target: "${{ env.UPLOAD_PATH }}"
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          passphrase: ${{ env.SERVER_SSH_KEY_PASSPHRASE }}

      - name: Fix dependencies & Fix Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{  env.REMOTE_USER }}
          key: ${{  env.SERVER_SSH_KEY }}
          passphrase: ${{  env.SERVER_SSH_KEY_PASSPHRASE }}
          envs: UPLOAD_PATH,REMOTE_USER,REMOTE_TARGET
          script_stop: true
          script: |
            cp $REMOTE_TARGET/shared/docker-compose.yml $UPLOAD_PATH/docker-compose.yml
            cp $REMOTE_TARGET/shared/docker-compose-base.yml $UPLOAD_PATH/docker-compose-base.yml
            cp $REMOTE_TARGET/shared/env.production $UPLOAD_PATH/.env.production
            cp $REMOTE_TARGET/shared/Makefile $UPLOAD_PATH/Makefile
            ln -s $REMOTE_TARGET/shared/.mysql_database_prod $UPLOAD_PATH/

      - name: remove old symbolic link & create new one
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{  env.REMOTE_USER }}
          key: ${{  env.SERVER_SSH_KEY }}
          passphrase: ${{  env.SERVER_SSH_KEY_PASSPHRASE }}
          envs: UPLOAD_PATH,REMOTE_TARGET,REMOTE_USER
          script_stop: true
          script: |
            ln -sfT $UPLOAD_PATH $REMOTE_TARGET/master
            cd $UPLOAD_PATH && make pull && make start
